---


- hosts: all
  become: true
  tasks:

   - name: update repository index 
     ansible.builtin.shell:
        cmd: "dnf makecache" 

   - name: install apache2 package
     ansible.builtin.dnf:
        name: httpd
        state: latest

   - name: add php support for apache
     ansible.builtin.dnf:
        name: php 
        state: latest
