---

- hosts: all
  become: true
  pre_tasks:
    - name: install updates (RedHat)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 and php for Ubuntu servers
      tags: web_servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 and php for RedHat servers
      tags: web_servers
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"
- hosts: db_servers
  become: true
  tasks:
  
    - name: install mariadb package (RedHat)
      tags: db_servers
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "RedHat"
  
    - name: install mariadb package (Ubuntu)
      tags: db_servers
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
- hosts: file_servers
  become: true
  tasks:

    - name: install samba package (RedHat)
      tags: file_servers
      package:
        name: samba
        state: latest
